### ISSUE TITLE
Pod Install Issue

### ISSUE THREAD

**Issue by StartupeKIT** [travelpayouts/travel-app-ios#11]
I get the following is there something missing in the assets or repo

Fetching xcpretty-travis-formatter 1.0.0
Using googleauth 0.6.7
Using google-cloud-core 1.3.2
Using google-api-client 0.23.9
Fetching google-cloud-storage 1.16.0
Installing json 2.2.0 with native extensions
Installing unf_ext 0.0.7.6 with native extensions
Installing xcpretty-travis-formatter 1.0.0
Installing google-cloud-storage 1.16.0
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/moabedin/Downloads/travel-app-ios-master/vendor/bundle/ruby/2.3.0/gems/json-2.2.0/ext/json/ext/generator
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20191221-16342-1nda7st.rb extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /Users/moabedin/Downloads/travel-app-ios-master/vendor/bundle/ruby/2.3.0/gems/json-2.2.0 for inspection.
Results logged to /Users/moabedin/Downloads/travel-app-ios-master/vendor/bundle/ruby/2.3.0/extensions/universal-darwin-18/2.3.0/json-2.2.0/gem_make.out

An error occurred while installing json (2.2.0), and Bundler cannot continue.
Make sure that `gem install json -v '2.2.0' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  cocoapods was resolved to 1.8.1, which depends on
    cocoapods-core was resolved to 1.8.1, which depends on
      algoliasearch was resolved to 1.27.1, which depends on
        json

**Comment by voidless** [comment]
Try installing macOS SDK Headers package before trying again
It should be located on your mac here: /Library/Developer/CommandLineTools/Packages

**Comment by StartupeKIT** [comment]
Thanks Voidless nut i get this issue the only error during build

Analyzing dependencies
Downloading dependencies
Installing Appodeal (2.4.10)

[!] Error installing Appodeal
[!] /usr/bin/curl -f -L -o /var/folders/hm/f2fh6dls43d1rx8dw7t30ws80000gn/T/d20200104-826-1iuvn1h/file.zip https://s3-us-west-1.amazonaws.com/appodeal-ios/2.4.10/cocoapods/Appodeal.zip --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  3  503M    3 19.5M    0     0  62998      0  2:19:44  0:05:26  2:14:18     0
curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54

**Comment by voidless** [comment]
Looks like a connectivity error, please try to run `bundle exec pod install` a few more times
It happens sometimes with Appodeal library
We will update the app to the latest Appodeal version soon which should improve this because the latest Appodeal version is 10 times smaller

**Comment by voidless** [comment]
Tuns out latest stable Appodeal is still 500mb, but latest beta is 10 times smaller
We've released version 6.2 with latest stable Appodeal so it may not be able to fix your issue

Instead you can update required version of Appodeal to the latest beta in the `Podfile` to `'~> 2.6.0'` and run `bundle exec pod install` again
