### ISSUE TITLE
App Store Publish

### ISSUE THREAD

**Issue by PolarisSoftDev** [travelpayouts/travel-app-ios#14]
I built an app with this template. some changes.
But App Store doesn't accept my submission.

======
Guideline 4.3 - Design

We noticed that your app provides the same feature set as other apps submitted to the App Store; it simply varies in content or language, which is considered a form of spam.

The next submission of this app may require a longer review time, and this app will not be eligible for an expedited review until this issue is resolved.

Next Steps

- Review the Design section of the App Store Review Guidelines.
- Ensure your app is compliant with all sections of the App Store Review Guidelines and the Terms & Conditions of the Apple Developer Program.
- Once your app is fully compliant, resubmit your app for review.

When creating multiple apps where content is the only varying element, you should offer a single app to deliver differing content to customers. If you would like to offer this content for purchase, it would be appropriate to use the in-app purchase API.

Alternatively, you may consider creating a web app, which looks and behaves similar to a native app when the customer adds it to their Home screen. Refer to the Configuring Web Applications section of the Safari Web Content Guide for more information.

Submitting apps designed to mislead or harm customers or evade the review process may result in the termination of your Apple Developer Program account. Review the Terms & Conditions of the Apple Developer Program to learn more about our policies regarding termination.
=======

Could you tell me a solution for this problem?

**Comment by PolarisSoftDev** [comment]
======================================
Dear Developer,

We identified one or more issues with a recent delivery for your app, "LoonyTrips" 1.0 (2). Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

After you’ve corrected the issues, you can upload a new binary to App Store Connect.

Best regards,

The App Store Team
======================================

**Comment by tenetko** [comment]
Hello,

You can tell the Apple reviewer that you are a member of Travelpayouts affiliate program and that you use the Travelpayouts SDK to develop your app. You can also provide the Apple reviewer with the following links to clarify the details about your app:

[Travelpayouts Affiliate Agreement. ](https://support.travelpayouts.com/hc/en-us/articles/203956053)
[The composition of iOS app template.](https://support.travelpayouts.com/hc/en-us/articles/115001338972-The-composition-of-iOS-app-template)
[Creation of a mobile application using SDK.](https://support.travelpayouts.com/hc/en-us/articles/203854126-Creation-of-a-mobile-application-using-SDK)

Also, you can add a page with a list of partners in your application.

**Comment by PolarisSoftDev** [comment]
Hello,

My app was rejected again.
*****
Regarding 4.3, your app provides the same feature set as other apps submitted to the App Store; it simply varies in content or language, which is considered a form of spam.

When creating multiple apps where content is the only varying element, you should offer a single app to deliver differing content to customers. If you would like to offer this content for purchase, it would be appropriate to use the in-app purchase API.

Alternatively, you may consider creating a web app, which looks and behaves similar to a native app when the customer adds it to their Home screen. Refer to the Configuring Web Applications section of the Safari Web Content Guide for more information.
*****
What is the solution? and what is a page with a list of partners?
I want to publish my app to app store.

**Comment by PolarisSoftDev** [comment]
Yes, I've customized the app, changed the app name, bundle ID, icon, colors, texts.
And I've informed the App Store reviewer that I am a member of travelpayouts affiliate program.

**Comment by PolarisSoftDev** [comment]
But apple doesn't accept my app. What is the solution?

**Comment by tenetko** [comment]
Unfortunately, it seems that Apple has restricted their requirements for the applications. Customizing an app doesn't seem to be enough to ensure an approval. You can try the following:
- delete this app and connect account;
- create new ones, with another bundle ID;
- submit the app again and specify the aforementioned details about being an affiliate etc -- you might get another, less stern reviewer.

If that doesn't help, you have to add to your app some other functionality apart from flights/hotels search.

**Comment by PolarisSoftDev** [comment]
I am gonna add car_rental_link to my app. Which link should I use for car_rental_link? Also, can I add tours link, too?

**Comment by PolarisSoftDev** [comment]
Dear Developer,

We identified one or more issues with a recent delivery for your app, "LoonyTrips" 1.0 (1). Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

After you’ve corrected the issues, you can upload a new binary to App Store Connect.

Best regards,

The App Store Team

**Comment by tenetko** [comment]
Hello,

Regarding cars, you can add a Car Rental tab. To do this you need to join one car rental partner program from Travelpayouts programs. Then you will need to generate a partner link and add it to the `TravelpayoutsTravelApp/default_config.plist` file to parameter `car_rental_link`.

Regarding tours, I'm afraid there's no simple way to add a Tours tab. You will have to make your own application based on the template.

Regarding UIWebView, Apple has informed you that your delivery was successful, so you don't have to do anything with that for now. We will update this lib in one of the nearest releases.

**Comment by PolarisSoftDev** [comment]
=== You will have to make your own application based on the template. ===
Which template should I use?
Is this right?
https://github.com/KosyanMedia/Aviasales-iOS-SDK
