### ISSUE TITLE
random build version 1.0..0.2003130137 

### ISSUE THREAD

**Issue by gandhivish** [travelpayouts/travel-app-ios#15]
we have facing 1 issue we try to create build with version 1.0    but random 1.0..0.2003130137  like this is added every time when try to create archive for upload app on appstore.

**Comment by voidless** [comment]
This is normal, users will still see Version 1.0 on the AppStore (CFBundleShortVersionString)
CFBundleVersion (Build version) is updated on every release build to allow uploading multiple builds of the same version to the AppStore

If you really want to disable this behavior, you can add ```exit 0``` to the start of ```scripts/build-pre-actions.sh``` file

**Comment by gschaer** [comment]
I created a PR to fix the build version when two dots are showing. See #26.
