### ISSUE TITLE
How to reduce app size. Its very big, within 170mb.

### ISSUE THREAD

**Issue by ggalstian** [travelpayouts/travel-app-ios#16]
How to reduce app size. Its very big, within **170mb**. ?

**Comment by tpsupport** [comment]
Hello,
The app has been designed as a straightforward and easy-to-use template. To achieve this goal, it uses a number of libraries from CocoaPods, but these dependencies make the app heavier. Unfortunately, you cannot get rid of these libraries to reduce the app's size. But you can try developing your own lightweight app using our SDK and SDK template:
[Aviasales iOS SDK Core](https://github.com/KosyanMedia/Aviasales-iOS-SDK-Core)
[Aviasales iOS SDK](https://github.com/KosyanMedia/Aviasales-iOS-SDK)
