### ISSUE TITLE
Xcode 11.4 (11E146) build Errors

### ISSUE THREAD

**Issue by olegsila** [travelpayouts/travel-app-ios#17]
У меня Xcode Version 11.4 (11E146)

1) Если я использую стандартные настройки Xcode, то при build проека возникает ошибка
"Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2 compiler: /Users/user/Desktop/travelAppTravelpayouts/ios/travel-app-ios-6.2/Pods/AviasalesKit/Library/AviasalesKit.framework/Modules/AviasalesKit.swiftmodule/x86_64-apple-ios-simulator.swiftmodule"

2) После этого, прочитав https://github.com/Alamofire/Alamofire/issues/2990 я иду в build settings и меняю build libraries for distribution на YES. Снова запускаю проект и ошибка 
"<unknown>:0: error: using bridging headers with module interfaces is unsupported
Command CompileSwiftSources failed with a nonzero exit code". 
Почитав про ошибку https://stackoverflow.com/questions/59192371/xcode-11-2-1-error-command-compileswiftsources-failed-with-a-nonzero-exit-code прихожу к тому, что меняю build libraries for distribution на NO снова

3) Устанавливаю Swift 5.1.3 Toolchain https://swift.org/download/#releases. Захожу в toolchains в Xcode и выбираю 5.1.3. build libraries for distribution установлен NO. Получаю ошибку "Compiling for iOS 10.0, but module 'AviasalesKit' has a minimum deployment target of iOS 11.0: /Users/user/Desktop/travelAppTravelpayouts/ios/travel-app-ios-6.2/Pods/AviasalesKit/Library/AviasalesKit.framework/Modules/AviasalesKit.swiftmodule/x86_64-apple-ios-simulator.swiftmodule"

4) Все остается как в пункет 3, только в проекте IOS deployment target ставлю IOS 11.  Получаю список ошибок (скрин https://ibb.co/DpjC8vF). Увидел, что в ошибках есть appodeal. Попробовал вставить ссылку и собрать, убрать ссылку и собрать. Разницы не было.

5) Если использую Xcode установленный, build ios от 11.0, build libraries for distribution, то ошибка "<unknown>:0: error: using bridging headers with module interfaces is unsupported
Command CompileSwiftSources failed with a nonzero exit code"

Перед каждым билдом заходил в product --- clean build folder

Что делать? как собрать build?)

**Comment by tpsupport** [comment]
Здравствуйте!

Надо собирать проект в Xcode версии 11.3.1. Режим "build libraries for distribution" в ближайшее время не будет поддерживаться.

**Comment by olegsila** [comment]
ок, спасибо!

**Comment by olegsila** [comment]
Спасибо 👌
