### ISSUE TITLE
Deprecated API Usage

### ISSUE THREAD

**Issue by olegsila** [travelpayouts/travel-app-ios#18]
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of new apps that use UIWebView APIs starting from April 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information.

Есть ли в настоящий момент возможность как-то интегрировать прокат автомобилей в Travel App? или только в SDK версии самому писать код?

**Comment by tpsupport** [comment]
Библиотека для рекламы Appodeal использует deprecated UIWebView. У них вышла новая версия, обновим. Если приложение не проходит ревью, попробуйте отключить Appodeal.

По поводу проката автомобилей. Вы можете добавить вкладку с арендой автомобилей. Для этого необходимо вступить в партнерскую программу из списка [Программ Travelpayouts](https://www.travelpayouts.com/programs). Затем нужно сгенерировать партнерскую ссылку и вставить ее в файл `TravelpayoutsTravelApp/default_config.plist` в параметр `car_rental_link`.
