### ISSUE TITLE
Какой класс меняет цвет текста на кнопке поиска?

### ISSUE THREAD

**Issue by digisat** [travelpayouts/travel-app-ios#19]
Подскажите пожалуйста, какой класс меняет цвет на кнопке поиска в авиабилетах, отелях и на кнопке купить? Сейчас он белый, нужно заменить на другой.

**Comment by tpsupport** [comment]
К сожалению, сейчас можно переназначить только классы:
```
THEME_COLOR()
SECOND_THEME_COLOR()
SEARCH_FORM_BACKGROUND()
COMMON_BACKGROUND()
```
Возможно, сделаем в будущем, чтобы можно было изменить и цвет на кнопке поиска.
