### ISSUE TITLE
Ошибка ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted.

### ISSUE THREAD

**Issue by digisat** [travelpayouts/travel-app-ios#20]
Не могу найти, где используется UIWebView, чтобы убрать эту ошибку при загрузку приложения. Подскажите пожалуйста!

**Comment by tpsupport** [comment]
Добрый день!
Мы убрали эту ошибку в новой версии приложения. Рекомендуем дождаться обновления и обновиться. Новая версия будет доступна в понедельник.

Хорошего дня!

**Comment by digisat** [comment]
Спасибо! Есть ли у вас возможность сейчас сказать что нужно поменять или отправить исправленные файлы, нужно очень срочно.

**Comment by tpsupport** [comment]
Пока что можете обновиться до этой версии: https://github.com/travelpayouts/travel-app-ios/tree/develop
Она полностью рабочая, за исключением readme. В понедельник зарелизим версию с фиксами в readme.

**Comment by digisat** [comment]
Спасибо!

**Comment by tpsupport** [comment]
Рады помочь!

**Comment by digisat** [comment]
Ещё один вопрос, в какой версии Xcode собирать проект, так как в 11.5 выдаёт ошибку Module compiled with Swift 5.2.2 cannot be imported by the Swift 5.3 compiler

**Comment by digisat** [comment]
Уже поставил Xcode 11.4.1, ещё раз спасибо!
