### ISSUE TITLE
Search default parameters

### ISSUE THREAD

**Issue by nikeshakya** [travelpayouts/travel-app-ios#21]
I have changed default search parameters for flight origin, destination and default currency 
But when it runs, it keeps changing back to USD and Los Vegas.
Also how can I change default region.

**Comment by tpsupport** [comment]
Hello,

The default search parameters you set up in the app configuration, will be used only when you don't have the internet connection. When you do, they are pre-filled automatically, depending on your current location.

Unfortunately, you cannot change the default region.
