### ISSUE TITLE
Please add Progress Bar

### ISSUE THREAD

**Issue by FredRDewitt** [travelpayouts/travel-app-ios#22]
Hello,
Please add Progress Bar when searching for hotels, As it was in the previous version.

![Screen Shot ](https://user-images.githubusercontent.com/45330656/83330507-3f081380-a287-11ea-862b-fcbf6ae17853.png)

**Comment by tpsupport** [comment]
Hello,

We have switched to instant results mode intentionally. This screen shows search results as soon as it gets the hotels list from our server. Prices from the agencies are loading a bit longer than the hotels list, but users already see the search screen.
