### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by thodiamedia** [travelpayouts/travel-app-ios#23]
[!] CocoaPods could not find compatible versions for pod "SDWebImage":
  In snapshot (Podfile.lock):
    SDWebImage (= 5.6.1)

  In Podfile:
    AviasalesKit (from `https://ios.aviasales.ru/cocoapods/AviasalesKit_6.3.podspec`) was resolved to 6.3, which depends on
      SDWebImage (= 5.6.1)

None of your spec sources contain a spec satisfying the dependencies: `SDWebImage (= 5.6.1), SDWebImage (= 5.6.1)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by tpsupport** [comment]
Hi!

Sorry for late reply.
You can try to make `bundle exec pod update` again. 
Also you may not have a SDWebImage dependency specified (usually in Podfile).
About name/version/source repo – they look right. This version is present in the cocoapods repository, name and version are correct.

**Comment by thodiamedia** [comment]
Hello
I built the app and didn't encounter any errors. How do I change car rentals to Tour booking for both ios and android platforms?

**Comment by tpsupport** [comment]
Hello!
You can only turn off the rental cars tab, but there is no option to add another program into the app at this moment.
