### ISSUE TITLE
Receiving error that required module Neon is missing when building in xcode 11.5

### ISSUE THREAD

**Issue by carsor007** [travelpayouts/travel-app-ios#24]
Receiving error that required module Neon is missing when building in xcode 11.5

`<unknown>:0: error: missing required module 'Neon'
/travel-app-ios-6.3/Pods/AviasalesKit/Library/AviasalesKit.framework/Headers/JRSearchResultsSortingType.h:9:9: note: while building module 'JRMainFlowComponents' imported from /travel-app-ios-6.3/Pods/AviasalesKit/Library/AviasalesKit.framework/Headers/JRSearchResultsSortingType.h:9:
#import <JRMainFlowComponents/JRSearchResultsSortingType.h>

While building module 'JRMainFlowComponents' imported from travel-app-ios-6.3/Pods/AviasalesKit/Library/AviasalesKit.framework/Headers/JRSearchResultsSortingType.h:9:

While building module 'JRUIComponents' imported from /travel-app-ios-6.3/Pods/AviasalesKit/Library/JRMainFlowComponents.framework/Headers/JRMainFlowComponents-Swift.h:194:

 In file included from /travel-app-ios-6.3/Pods/AviasalesKit/Library/JRUIComponents.framework/Headers/JRUIComponents-umbrella.h:34:`

**Comment by tpsupport** [comment]
Hello,

It seems that you have changed something in Podfile that led to this error. We restarted the 6.3 Build in a public repository, and everything worked out correctly. The dependence on Neon is indicated in Podfile.

**Comment by carsor007** [comment]
This issue is now resolved on my end. Thank you.

**Comment by Neeraj3508** [comment]
> This issue is now resolved on my end. Thank you.

How you solved this one?
