### ISSUE TITLE
Module compiled cannot be imported. Swift 5.2.2 -> Swift 5.3

### ISSUE THREAD

**Issue by emmismtv** [travelpayouts/travel-app-ios#27]
`Module compiled with Swift 5.2.2 cannot be imported by the Swift 5.3 compiler: /Users/emmis/Downloads/travel-app-ios-6.3/Pods/AviasalesKit/Library/AviasalesKit.framework/Modules/AviasalesKit.swiftmodule/x86_64-apple-ios-simulator.swiftmodule`

**Comment by tpsupport** [comment]
Hello!
You should use Xcode 11.4.1 or 11.5 to compile it correctly.

**Comment by voidless** [comment]
Xcode 12.0.1 is now supported in version 6.4
