### ISSUE TITLE
Changing Bundle Display Name By Language

### ISSUE THREAD

**Issue by FredRDewitt** [travelpayouts/travel-app-ios#29]
I want my app name to be localized(English, French, German; ...), how do I do that?

Xcode 12.0.1
travel app ios 6.4

**Comment by nfnc1985** [comment]
Hello! You can set up the localization string in InfoPlist.string file. You can find many instructions, here is the [one](https://stackoverflow.com/questions/2871990/how-to-localize-bundle-display-name-in-iphone-app).
