### ISSUE TITLE
Changing colors from ASTJSC

### ISSUE THREAD

**Issue by f0r3s1** [travelpayouts/travel-app-ios#3]
> Fine-grained color customization can be configured in file ASTJRC.swift by overriding colors from the base class JRC.

It's not possible because you restricted this by using Pubic instead of Open:
<img width="635" alt="image" src="https://user-images.githubusercontent.com/15886508/62568446-d7b34a00-b895-11e9-99ed-e129eb2fab9d.png">

And when I trying to override I got the error:
<img width="832" alt="image" src="https://user-images.githubusercontent.com/15886508/62568495-f9accc80-b895-11e9-8691-cd06cc370d59.png">

Please let me know how I can fix it.

**Comment by voidless** [comment]
We plan to allow overriding all colors in JRC in the next version, to be released late in September.
You can however use swizzling to override colors right now thought it is a discouraged mechanism.

The is an integrated pod for swizzling in the app named JRSwizzle, you can use it for convenience.

**Comment by voidless** [comment]
Overriding colors is now available in travel-app-ios version 6.1
