### ISSUE TITLE
Module compiled with Swift 5.3 cannot be imported by the Swift 5.3.1

### ISSUE THREAD

**Issue by AlexIOSb** [travelpayouts/travel-app-ios#30]
<img width="832" alt="Знімок екрана 2020-11-23 о 12 27 00" src="https://user-images.githubusercontent.com/62012825/99951710-32243280-2d87-11eb-9252-664b792b0dd4.png">

Xcode version: 12.2

I guess you need to set the Build Libraries for Distribution option to Yes in your framework's build settings

Thanks for reply in advance

**Comment by tpsupport** [comment]
Hello!

For now, we can recommend you to use Xcode 12.1. We'll add supporting of 12.2 version in the next update.
