### ISSUE TITLE
Multiple buildtime errors - deprecations

### ISSUE THREAD

**Issue by riveraj33** [travelpayouts/travel-app-ios#33]
Hello. I receive multiple deprecation errors(11) . Please see the screenshot below. This is on an intel iMac on Catalina.
<img width="386" alt="Screen Shot 2021-02-03 at 11 30 17 AM" src="https://user-images.githubusercontent.com/34040656/106779392-ef979580-6614-11eb-8ed0-5a55e89c3751.png">

**Comment by tpsupport** [comment]
Hello,

Sorry for the delayed response.

Please disregard these errors since they are not critical. We are going to have them fixed in the next update.
