### ISSUE TITLE
Swift Compiler Error During Build

### ISSUE THREAD

**Issue by mubasherkhan** [travelpayouts/travel-app-ios#36]
Unable to build project on latest **Xcode Version 12.4 (12D4e)** 
`/Users/mubasherkhan/Downloads/travel-app-ios-6.4/TravelpayoutsTravelApp/Source/CommonSource/InfoScreen/InfoScreenRouter.swift:5:8: Module compiled with Swift 5.3 cannot be imported by the Swift 5.3.2 compiler: /Users/mubasherkhan/Downloads/travel-app-ios-6.4/Pods/AviasalesKit/Library/AviasalesKit.framework/Modules/AviasalesKit.swiftmodule/x86_64-apple-ios-simulator.swiftmodule`

**Comment by tpsupport** [comment]
Please use the Xcode version that you can find in the release notes.
