### ISSUE TITLE
Urgent! Problem with compile

### ISSUE THREAD

**Issue by koziejakub** [travelpayouts/travel-app-ios#38]
Please compile to latest xCode (12.4), as it is not possible to download an older version on a Macbook. This is very urgent!

<img width="1440" alt="Screenshot 2021-03-21 at 13 26 01" src="https://user-images.githubusercontent.com/74066052/111904958-9f9c5300-8a49-11eb-8e1e-bed96ff0a9f1.png">

**Comment by tpsupport** [comment]
Hello! You should use the Xcode version that is specified in the release notes.

**Comment by koziejakub** [comment]
It is not possible to download the old version. Apple blocks installation
of the old version.

**Comment by tpsupport** [comment]
We kindly ask you to use the Xcode version that can found in the release notes.

**Comment by koziejakub** [comment]
I don't have a possibillity to this version, because apple release a new
version.

**Comment by glassoff** [comment]
You can download Xcode 12.0.1 from https://developer.apple.com/download/more/
