### ISSUE TITLE
Hosting IOS app on Amazon

### ISSUE THREAD

**Issue by Oxko** [travelpayouts/travel-app-ios#39]
Hi, 

I want to submit my IOS app on Amazon. I'm not sure how to link the app to amazon, or if that's even possible with this project. I have my own website for this app, but it's not a web app. Is there a way I can link it using the second method(zip file)?

Thanks in advance.

<img width="1040" alt="Screenshot 2021-04-24 at PM 7 26 59" src="https://user-images.githubusercontent.com/78652916/115967462-0de5a100-a533-11eb-87ac-b1e04395894f.png">

**Comment by tpsupport** [comment]
Hi! 

Unfortunately, the iOS project can be uploaded only to AppStore.

**Comment by Oxko** [comment]
Ok thanks.
