### ISSUE TITLE
Avia to TravelPayouts SDK

### ISSUE THREAD

**Issue by zencaa** [travelpayouts/travel-app-ios#4]
Hi whats the best way to udate Avia SDK to TravelPayouts SDK?

**Comment by annaTP** [comment]
Hello @zencaa 
You need to transfer your settings to the new SDK, such as app's bundle id and team id, and make the version newer than the current app's version. You will also want to set the name, icon, splash screen, basic colours and all the parameters in the config. Make sure to check that the new app is installed over the old one (debug version — over debug version). Then you can upload the app to the app store
