### ISSUE TITLE
Did you removed the waiting screen ?

### ISSUE THREAD

**Issue by patriksharma** [travelpayouts/travel-app-ios#41]
As I see you have removed the waiting screen. Basically Appodeal is not providing API key and I have used google ads instead of that ? 

May I know is there a way we can still use waiting screen ?

**Comment by patriksharma** [comment]
@voidless @travelpayouts-github  It will be great if you help me to get waiting screen back ? I won't trust appodeal and they are like on high dose who investigate email before giving account access.

it will be best I will integrate my own Admob ID and publish my app to store ... please help :)

**Comment by patriksharma** [comment]
@voidless @travelpayouts-github  would be great help if you respond on this ASAP.  Its difficult or looks impossible to deal with appodeal . I have signup there on last Friday but they didn't responded yet.  So If I get waiting screen I can implement by own Google Ads or any other framework directly. Please help

**Comment by tpsupport** [comment]
@patriksharma we'll be adding Appodeal soon, sorry for the inconvenience.

**Comment by patriksharma** [comment]
@tpsupport  Thanks a lot. Please re-add Waiting Screen.

**Comment by tpsupport** [comment]
@patriksharma here's our update: https://github.com/travelpayouts/travel-app-ios/releases/tag/6.5.1

**Comment by patriksharma** [comment]
Thanks for the update, nows adsmanager class get called
