### ISSUE TITLE
Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1

### ISSUE THREAD

**Issue by ggalstian** [travelpayouts/travel-app-ios#5]
Please help solve this issue! I can not run application!
this error!
**Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1**
[https://prnt.sc/plwf8v](url)

**Comment by vlshevtsov** [comment]
The problem is caused by new Xcode version. You have to switch Swift version to 5.0 for your Xcode project. Or, you can wait for a fix update of SDK repository, it will be updated in the nearest days.

**Comment by ggalstian** [comment]
ok, Thank you!

**Comment by ggalstian** [comment]
I can not change swift version! How I shoul change.??

**Comment by voidless** [comment]
You can't change swift version. You need to use a compatible Xcode version.
travel-app-ios 6.0 works with Xcode 10.3
travel-app-ios 6.1 works with Xcode 11.0 and 11.1
Just released Xcode 11.2 is not supported currently
