### ISSUE TITLE
Hello. When will the sdk be updated for Xcode 13? Previous response said end on quarter. Still on track?

### ISSUE THREAD

**Issue by riveraj33** [travelpayouts/travel-app-ios#50]
We really need to get onto Xcode 13. Please, is this still on track for the end of this quarter?

**Comment by tpsupport** [comment]
Hi!

Unfortunately, we can't make it by the end of December. We're planning to release the updated version in January. 
Sorry for the inconvenience caused.

**Comment by riveraj33** [comment]
Hi there. I'm hoping that this is still on track to be released this month for Xcode 13?
