### ISSUE TITLE
Find hotels button doesn't work if app presents HotelViewController on the latest sdk version

### ISSUE THREAD

**Issue by harrylefit** [travelpayouts/travel-app-ios#55]
Hi guys, 

I upgraded to the latest sdk version but the hotel screen doesn't work properly. The hotel screen would be closed after I tapped `Find hotels` button on this screen. It works perfectly on the previous sdk version. Can you check and fix it on the latest version? 

![image](https://user-images.githubusercontent.com/20136040/154787657-429e7c66-cedf-43e2-9812-5cbee3b61dc2.png)

**Comment by tpsupport** [comment]
Hello! Could you please send us the details regarding the issue (including the link to your app and the log file) at the email address support@travelpayouts.com? We will be glad to help!
