### ISSUE TITLE
Car Rental Service - Why its a web page ?

### ISSUE THREAD

**Issue by patriksharma** [travelpayouts/travel-app-ios#7]
Hello,

First of all thanks a lot for new Update.

I have checked your new service of car rental and its integration. Its integration is simple web page , So I have created a link and added it to the App. As I saw its a web page opening up but its also showing an option to download there own app from app store. So it looks bit confusing to the people. 
![unnamed](https://user-images.githubusercontent.com/383524/68064838-00d56080-fd47-11e9-94b9-c525d7081ff8.jpg)

**Comment by voidless** [comment]
Hello!

Currently we can only provide web view integration with car rental services. It also allows you to select any car rental service we support, or even any service you can find on the internet.

We will cut out banners like this for Rentalcars website in the next Travel App version. We plan to support cutting banners on other websites later.
