### ISSUE TITLE
Duplicate GoogleUtilities Targets Causing Build Error

### ISSUE THREAD

**Issue by Norzareen** [travelpayouts/travel-app-ios#76]
I'm encountering a build error in release 6.7.1 due to duplicate GoogleUtilities targets. The error message is as follows:

```
note: Building targets in dependency order
error: Multiple commands produce '/Users/zareen/Library/Developer/Xcode/DerivedData/TravelpayoutsTravelApp/Build/Intermediates.noindex/ArchiveIntermediates/TravelpayoutsTravelApp/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GoogleUtilities.framework'
   note: Target 'GoogleUtilities-00567490' (project 'GoogleUtilities') has create directory command with output '/Users/zareen/Library/Developer/Xcode/DerivedData/TravelpayoutsTravelApp/Build/Intermediates.noindex/ArchiveIntermediates/TravelpayoutsTravelApp/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GoogleUtilities.framework'
   note: Target 'GoogleUtilities-b9437b04' (project 'GoogleUtilities') has create directory command with output '/Users/zareen/Library/Developer/Xcode/DerivedData/TravelpayoutsTravelApp/Build/Intermediates.noindex/ArchiveIntermediates/TravelpayoutsTravelApp/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GoogleUtilities.framework'
```
![229204001-fbbffc3b-1c76-4f86-97f6-651fa087fe75](https://user-images.githubusercontent.com/111111928/229274612-5ef08718-1fc7-451b-8db6-13276ed20bf4.png)

Is any way to fix this?

**Comment by bartleby** [comment]
same problem

**Comment by kattouf** [comment]
Can you try [this](https://github.com/firebase/firebase-ios-sdk/issues/4087#issuecomment-545841819) solution?

**Comment by Norzareen** [comment]
Hi kattouf, I've tried the solution you suggested, but unfortunately, the problem still persists.

**Comment by jonu2528** [comment]
This is a bug on Apple's backend validation?

"The app references non-public selectors in Payload/TravelpayoutsTravelApp.app/TravelpayoutsTravelApp: filterButtonAction:, handleGestureRecognizer:, pendingAnimation, promise"

**Comment by kattouf** [comment]
@jonu2528 Yes, it's Apple side, try resubmitting app later

**Comment by RankoR** [comment]
@kattouf thanks, updating to 6.7.2 worked
