### ISSUE TITLE
Project doesn't build

### ISSUE THREAD

**Issue by AlexGee17** [travelpayouts/travel-app-ios#85]
Hello!

Project doesn't build, Xcode just hangs for eternity trying to build your project without any success. 
<img width="343" alt="Screenshot1" src="https://github.com/travelpayouts/travel-app-ios/assets/13656162/5a754ac8-96ad-457d-a0f7-9c678016339b">
<img width="215" alt="Screenshot2" src="https://github.com/travelpayouts/travel-app-ios/assets/13656162/1205a184-cf92-4ffc-8194-9831c67ecd04">

**Comment by kattouf** [comment]
Hello! Please use Xcode 14.2 (14C18) to fix it.

**Comment by AlexGee17** [comment]
Thank you! It works with old Xcode version
