### ISSUE TITLE
Xcode 15 is around the corner. Will this be updated to support it?

### ISSUE THREAD

**Issue by riveraj33** [travelpayouts/travel-app-ios#87]
Xcode 15. In previous years this package gets updated around 5-6 months after the release of a new yearly Xcode version. Will this be updated before Xcode 15 or shortly thereafter? 5 months is way too long, thanks.

**Comment by tpsupport** [comment]
Hello,

The latest version has been already released, and we update it only in the event of critical bugs. We kindly request your patience as we're working on developing the new version of the application.
