### ISSUE TITLE
Can you add an image here?

### ISSUE THREAD

**Issue by OurHaystack** [travelpayouts/travel-app-ios#90]
You can change search forms titles in AppLocalizations.swift file. Uncomment and edit a variable to change corresponding search form title.

Can you also add an image here?

    override var ticketsSearchFormTitle: String {
    return NSLocalizedString("Trippo Flights", comment: "Trippo Flights")
    }
    override var hotelsSearchFormTitle: String {
    return "Trippo Hotels"
    }
    }

**Comment by tpsupport** [comment]
Hello!

Apologies for the delayed response.

This parameter only allows making text changes in the search form title. For now, there is no possibility to add images into the search form. 

You can find all the possibilities of Travel app customization [here](https://github.com/travelpayouts/travel-app-ios).
