### ISSUE TITLE
Will this be updated for Xcode 15?

### ISSUE THREAD

**Issue by riveraj33** [travelpayouts/travel-app-ios#93]
This is only compatible with Xcode 14.2 which is very old. When will this be updated to the latest Xcode or is something else going on? Should we move on to another provider?

**Comment by tpsupport** [comment]
Hello! Unfortunately, we do not plan to update the existing template. But the new version of the Travel App, which will be compatible with Xcode 15, is in progress. There is no ETA for the release. As soon as it is ready, we will inform our partners in the newsletter.
