### ISSUE TITLE
Error occurred: Cannot find 'viewController' in scope.

### ISSUE THREAD

**Issue by anatoll73** [travelpayouts/travel-app-ios#94]
Hello. I created a clean application and integrated a template project into it according to your instructions. But at the last stage, when adding search screens, an error occurred: Cannot find 'viewController' in scope.
What am I doing wrong? Any help is helpful.
Thank you

<img width="1280" alt="Screen" src="https://github.com/travelpayouts/travel-app-ios/assets/146563136/bfd3a524-34b2-43ab-b602-c8fb4cbbce68">
`
import UIKit
import ASTemplateConfiguration

class FlightsViewController: UIViewController {
    
    override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view.
        let flightsViewController = AviasalesViewControllersFactory.shared.flightsViewController()
        let hotelsViewController = AviasalesViewControllersFactory.shared.hotelsViewController()
        let carRentalViewController = AviasalesViewControllersFactory.shared.carRentalViewController()

        viewController.present(flightsViewController, animated: true, completion: nil)
    }
    
}`

**Comment by tpsupport** [comment]
Hi,
If you'd like to use the template, you should follow the instructions at the beginning of the README — How to build your own app using the template project: https://github.com/travelpayouts/travel-app-ios/blob/d32c015c5fb50864ea4cb3f6d3740f0822e556eb/README.md?plain=1. 
Currently, you are following the integration guide for an existing application.
