### ISSUE TITLE
Travel App SDK update for iPhone IOS 17?

### ISSUE THREAD

**Issue by OurHaystack** [travelpayouts/travel-app-ios#95]
I see that a statement was made below with regards to a new updated version etc. Any timeframes for 2024?

"Hello! Unfortunately, we do not plan to update the existing template. But the new version of the Travel App, which will be compatible with Xcode 15, is in progress. There is no ETA for the release. As soon as it is ready, we will inform our partners in the newsletter."

**Comment by tpsupport** [comment]
Hello! Unfortunately, we don't have a specific timeline for when the new version of the Travel App will be available. Rest assured, we'll inform our partners as soon as it's ready.
